version: '3.7'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app-network

  ordersystem:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ordersystem
    restart: always
    depends_on:
      - mysql
      - rabbitmq
    ports:
      - "8000:8000"
      - "8080:8080"
    working_dir: /src/cmd/ordersystem
    command:
      - /bin/bash
      - -c
      - |
        /usr/local/bin/wait-for-it.sh mysql 3306 && goose -dir /src/db/migrations mysql 'root:root@tcp(mysql:3306)/orders' up && go run main.go wire_gen.go
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: