services:
  mysql:
    image: mysql:5.7
    dns:
      - 8.8.8.8
      - 1.1.1.1    
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mysql", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  ordersystem:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ordersystem
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    ports:
      - "8000:8000"
      - "8080:8080"
      - "50051:50051" 
    working_dir: /src/cmd/ordersystem
    command:
      - /bin/bash
      - -c
      - |
        goose -dir /src/db/migrations mysql 'root:root@tcp(mysql:3306)/orders' up && go run main.go wire_gen.go  

volumes:
  mysql_data:
